applications:
  - name: ${app_name}
    project: default
    source:
      repoURL: ${repo_url}
      targetRevision: HEAD
      path: ${repo_path}
    destination:
      server: https://kubernetes.default.svc
      namespace: ${app_namespace}
    syncPolicy:
      automated: {}
      syncOptions:
        - CreateNamespace=true

  - name: tenants-applicationset
    project: default
    source:
      repoURL: ${repo_url}
      targetRevision: HEAD
      path: argocd      # Ordner, in dem deine applicationset-tenants.yaml liegt
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated: {}