apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants-helm
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/phwildzeiss/KeyStore-gitops
        revision: HEAD
        directories:
          - path: tenants/*
        requeueAfterSeconds: 30
  template:
    metadata:
      name: '{{path.basename}}-app'
      annotations:
        argocd-image-updater.argoproj.io/image-list: |
          frontend=docker.io/phwildzeiss/k8s-multi-tenant-frontend:latest,
          inventory=docker.io/phwildzeiss/k8s-multi-tenant-inventory:latest,
          orders=docker.io/phwildzeiss/k8s-multi-tenant-order-service:latest
        argocd-image-updater.argoproj.io/frontend.helm.image-name: images.frontend.repository
        argocd-image-updater.argoproj.io/frontend.helm.image-tag: images.frontend.tag
        argocd-image-updater.argoproj.io/frontend.update-strategy: digest
        argocd-image-updater.argoproj.io/inventory.helm.image-name: images.inventory.repository
        argocd-image-updater.argoproj.io/inventory.helm.image-tag: images.inventory.tag
        argocd-image-updater.argoproj.io/inventory.update-strategy: digest
        argocd-image-updater.argoproj.io/orders.helm.image-name: images.orders.repository
        argocd-image-updater.argoproj.io/orders.helm.image-tag: images.orders.tag
        argocd-image-updater.argoproj.io/orders.update-strategy: digest
        argocd-image-updater.argoproj.io/write-back-method: argocd
        argocd-image-updater.argoproj.io/helm-image-policy: enabled
        argocd-image-updater.argoproj.io/frontend.force-update: "true"

    spec:
      project: default
      source:
        repoURL: https://github.com/phwildzeiss/KeyStore-gitops
        targetRevision: HEAD
        path: helm-app                          # Chart-Verzeichnis
        helm:
          valueFiles:
            - '../{{path}}/values.yaml'            # Tenant-spezifische Werte
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'          # z. B. tenant-a
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
