apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants-helm
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/phwildzeiss/KeyStore-gitops
        revision: HEAD
        directories:
          - path: tenants/*
        requeueAfterSeconds: 30
  template:
    metadata:
      name: '{{path.basename}}-app'
      annotations:
        argocd-image-updater.argoproj.io/image-list: |
          docker.io/phwildzeiss/k8s-multi-tenant-order-service,
          docker.io/phwildzeiss/k8s-multi-tenant-inventory,
          docker.io/phwildzeiss/k8s-multi-tenant-frontend

        argocd-image-updater.argoproj.io/docker.io.phwildzeiss.k8s-multi-tenant-order-service.helm-value: images.order.tag
        argocd-image-updater.argoproj.io/docker.io.phwildzeiss.k8s-multi-tenant-order-service.update-strategy: name

        argocd-image-updater.argoproj.io/docker.io.phwildzeiss.k8s-multi-tenant-inventory.helm-value: images.inventory.tag
        argocd-image-updater.argoproj.io/docker.io.phwildzeiss.k8s-multi-tenant-inventory.update-strategy: name

        argocd-image-updater.argoproj.io/docker.io.phwildzeiss.k8s-multi-tenant-frontend.helm-value: images.frontend.tag
        argocd-image-updater.argoproj.io/docker.io.phwildzeiss.k8s-multi-tenant-frontend.update-strategy: name
    spec:
      project: default
      source:
        repoURL: https://github.com/phwildzeiss/KeyStore-gitops
        targetRevision: HEAD
        path: helm-app                          # Chart-Verzeichnis
        helm:
          valueFiles:
            - '../{{path}}/values.yaml'            # Tenant-spezifische Werte
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'          # z. B. tenant-a
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
