apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants-helm
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/phwildzeiss/KeyStore-gitops
        revision: HEAD
        directories:
          - path: tenants/*
        requeueAfterSeconds: 30
  template:
    metadata:
      name: '{{path.basename}}-app'
      annotations:
        argocd-image-updater.argoproj.io/image-list: |
          order-service=docker.io/phwildzeiss/k8s-multi-tenant-order-service
          inventory-service=docker.io/phwildzeiss/k8s-multi-tenant-inventory
          frontend=docker.io/phwildzeiss/k8s-multi-tenant-frontend

        argocd-image-updater.argoproj.io/order-service.helm.image-name: images.order.repository
        argocd-image-updater.argoproj.io/order-service.helm.image-tag: images.order.tag
        argocd-image-updater.argoproj.io/order-service.update-strategy: name
        argocd-image-updater.argoproj.io/order-service.allow-tags: ^[0-9]{14}$

        argocd-image-updater.argoproj.io/inventory-service.helm.image-name: images.inventory.repository
        argocd-image-updater.argoproj.io/inventory-service.helm.image-tag: images.inventory.tag
        argocd-image-updater.argoproj.io/inventory-service.update-strategy: name
        argocd-image-updater.argoproj.io/inventory-service.allow-tags: ^[0-9]{14}$

        argocd-image-updater.argoproj.io/frontend.helm.image-name: images.frontend.repository
        argocd-image-updater.argoproj.io/frontend.helm.image-tag: images.frontend.tag
        argocd-image-updater.argoproj.io/frontend.update-strategy: name
        argocd-image-updater.argoproj.io/frontend.allow-tags: ^[0-9]{14}$

        argocd-image-updater.argoproj.io/write-back-method: argocd
        argocd-image-updater.argoproj.io/helm-image-policy: enabled

    spec:
      project: default
      source:
        repoURL: https://github.com/phwildzeiss/KeyStore-gitops
        targetRevision: HEAD
        path: helm-app                          # Chart-Verzeichnis
        helm:
          valueFiles:
            - '../{{path}}/values.yaml'            # Tenant-spezifische Werte
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'          # z. B. tenant-a
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
