apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: {{.Values.tenantName}}
spec:
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: {{.Values.tenantName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      serviceAccountName: {{.Values.tenantName}}-sa
      containers:
        - name: inventory-service
          image: bennimoser/k8s-multi-tenant-inventory
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: key-store-config
            - secretRef:
                name: key-store-secret
            - secretRef:
                name: {{.Values.tenantName}}-db-secret   
          resources:
            requests:
              memory: "{{.Values.resources.requests.memory}}"
              cpu: "{{.Values.resources.requests.cpu}}"
            limits:
              memory: "{{.Values.resources.limits.memory}}"
              cpu: "{{.Values.resources.limits.cpu}}"
          securityContext:
            runAsNonRoot: {{.Values.securityContext.runAsNonRoot}}
            runAsUser: {{.Values.securityContext.runAsUser}}