apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.tenantName}}-ingress
  namespace: {{.Values.tenantName}}
  annotations:
    # nginx.ingress.kubernetes.io/auth-url: "http://$host/oauth2/auth"
    # nginx.ingress.kubernetes.io/auth-signin: "http://$host/oauth2/start?rd=$escaped_request_uri"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: "/{{.Values.tenantName}}"
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
